from pathlib import Path

from PIL import Image, ImageChops


panel = Image.open(Path(__file__).parent / "resources/cipher_matrix.png")
solid = Image.open(Path(__file__).parent / "resources/solid.png")
plate01 = Image.open(Path(__file__).parent / "resources/plate_01.png")
plate02 = Image.open(Path(__file__).parent / "resources/plate_02.png")
plate03 = Image.open(Path(__file__).parent / "resources/plate_03.png")
plate11 = Image.open(Path(__file__).parent / "resources/plate_11.png")
plate12 = Image.open(Path(__file__).parent / "resources/plate_12.png")
plate13 = Image.open(Path(__file__).parent / "resources/plate_13.png")
plate21 = Image.open(Path(__file__).parent / "resources/plate_21.png")
plate22 = Image.open(Path(__file__).parent / "resources/plate_22.png")
plate23 = Image.open(Path(__file__).parent / "resources/plate_23.png")
plate31 = Image.open(Path(__file__).parent / "resources/plate_31.png")
plate32 = Image.open(Path(__file__).parent / "resources/plate_32.png")
# plate33 = Image.open(Path(__file__).parent / "resources/plate_33.png")
d01 = ImageChops.subtract(solid, plate01)
d02 = ImageChops.subtract(solid, plate02)
d03 = ImageChops.subtract(solid, plate03)
d11 = ImageChops.subtract(solid, plate11)
d12 = ImageChops.subtract(solid, plate12)
d13 = ImageChops.subtract(solid, plate13)
d21 = ImageChops.subtract(solid, plate21)
d22 = ImageChops.subtract(solid, plate22)
d23 = ImageChops.subtract(solid, plate23)
d31 = ImageChops.subtract(solid, plate31)
d32 = ImageChops.subtract(solid, plate32)
# d33 = ImageChops.subtract(solid, plate33)
composed = Image.new("RGBA", solid.size, None)
composed.paste(d01, mask=d01)
composed.paste(d02, mask=d02)
composed.paste(d03, mask=d03)
composed.paste(d11, mask=d11)
composed.paste(d12, mask=d12)
composed.paste(d13, mask=d13)
composed.paste(d21, mask=d21)
composed.paste(d22, mask=d22)
composed.paste(d23, mask=d23)
composed.paste(d31, mask=d31)
composed.paste(d32, mask=d32)
# composed.paste(d33, mask=d33)
panel.paste(composed, mask=composed)
panel.show()
